CREATE TABLE suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE NOT NULL,
    address varchar NOT NULL,
    vat_number varchar,
    iban varchar NOT NULL
);

CREATE TABLE clients (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE NOT NULL,
    address varchar NOT NULL,
    vat_number varchar
);

CREATE TABLE invoices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer references clients NOT NULL,
    number varchar UNIQUE NOT NULL,
    -- No check constraint to be able to create test fixtures with past values.
    date date NOT NULL,
    due_date date CHECK (due_date >= date) NOT NULL,
    vat_rate smallint CHECK (vat_rate >= 0) NOT NULL,
    supplier_name varchar NOT NULL,
    supplier_address varchar NOT NULL,
    supplier_vat_number varchar,
    supplier_iban varchar NOT NULL,
    client_name varchar NOT NULL,
    client_address varchar NOT NULL,
    client_vat_number varchar
);

CREATE TABLE line_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id integer references invoices NOT NULL,
    name varchar NOT NULL,
    price smallint NOT NULL,
    quantity smallint CHECK (quantity > 0) NOT NULL
);